services:
  postgres_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: commers
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: panda@gmail.com
      PGADMIN_DEFAULT_PASSWORD: panda
    restart: always
    ports:
      - 5050:80