// <auto-generated />
using ChubbyPandaEcommerce.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChubbyPandaEcommerce.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220202044338_ProductsAddData")]
    partial class ProductsAddData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChubbyPandaEcommerce.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Figurine anime",
                            ImageUrl = "https://www.ubuy.za.com/productimg/?image=aHR0cHM6Ly9tLm1lZGlhLWFtYXpvbi5jb20vaW1hZ2VzL0kvNzFZcjErbXRDMkwuX0FDX1NMMTUwMF8uanBn.jpg",
                            Price = 9.99m,
                            Title = "Figur"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Figurine anime",
                            ImageUrl = "https://m.media-amazon.com/images/I/61CXYX0Qy2L._AC_SY679_.jpg",
                            Price = 9.99m,
                            Title = "Tanya"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
